#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta9

PRODUCT_COPY_FILES += \
    vendor/samsung/gta9/proprietary/system_ext/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/init.vtservice.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/BtInfo_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/BtInfo_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/HpImpedance_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/HpImpedance_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/MicInfo_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/MicInfo_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackACF_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackACF_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackDRC_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackDRC_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackHCF_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackHCF_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolAna_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolDigi_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Playback_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Playback_ParamTreeView.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Playback_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordDMNR_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordDMNR_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordFIR_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordFIR_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordVolUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordVolUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordVol_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RecordVol_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Record_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Record_ParamTreeView.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Record_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RingbackVolUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RingbackVolUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RingbackVol_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/RingbackVol_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SmartPa_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SmartPa_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SoundEnhancement_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SoundEnhancement_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechDMNR_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechDMNR_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechEchoRef_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechGeneral_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechGeneral_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechMagiClarity_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechNetwork_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechNetwork_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechVolUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechVolUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechVol_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/SpeechVol_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Speech_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Speech_ParamTreeView.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Speech_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/USBCall_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/USBCall_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/USBDevice_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/USBDevice_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Ultrasound_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Ultrasound_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/UplinkConfiguration_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPDMNR_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPDMNR_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPGeneral_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPGeneral_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPVolUI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPVolUI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPVol_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPVol_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIP_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIP_ParamTreeView.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIP_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2DMNR_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2General_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2General_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2UI_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2UI_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2_ParamTreeView.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoIPv2_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWDspAec_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWDspAec_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWEngineFeature_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWHwVad_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWHwVad_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWMicSetting_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWMicSetting_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWVoiceCommand_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VolumeGainMapUL_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VolumeGainMap_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/VolumeGainMap_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Volume_AudioParam.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/audio_param_huaqin/EUR/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param_huaqin/EUR/Volume_ParamUnitDesc.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/BSTAI_Scene_181_emb_1280_34c:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/BSTAI_Scene_181_emb_1280_34c \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/BSTAI_Scene_181_emb_1280_34c.BSTAI:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/BSTAI_Scene_181_emb_1280_34c.BSTAI \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/beauty_new.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/beauty_new.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/beautybokeh_new.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/beautybokeh_new.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bokeh_otp_default.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bokeh_otp_default.dat \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_3ddns.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_3ddns.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_ai:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_ai \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_ai_preview:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_ai_preview \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_ai_sample:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_ai_sample \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_aibokeh.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_aibokeh.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_dualbokeh.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_dualbokeh.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_filter_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_filter_config.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_night.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_night.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_panorama_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_panorama_config.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_sef.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_sef.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_stick.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_stick.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bst_swad_param_list.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bst_swad_param_list.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bstai_aidoc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bstai_aidoc \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bstai_hdr:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bstai_hdr \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bstaicorner_aidoc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bstaicorner_aidoc \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/bsthand.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/bsthand.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/control_param_aiscene_encode.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/control_param_aiscene_encode.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/control_param_dsremove_enablestretch.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/control_param_dsremove_enablestretch.txt \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/distortion_param.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/distortion_param.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/foodmode_param_encode.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/foodmode_param_encode.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/hdr_dump.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/hdr_dump.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/hdrcfg.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/hdrcfg.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/param_doc.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/param_doc.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/bstcfg/swad_calib.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bstcfg/swad_calib.bin \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/colortone_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/colortone_arrays.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/filter_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/filter_config.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/food_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/food_config.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hdr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_arrays.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hdr_face_detected_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdr_face_detected_arrays.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hdrusercfg.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hdrusercfg.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hqcfg/hq_palm_detect.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hqcfg/hq_palm_detect.bin \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hqcfg/hq_palm_detect.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hqcfg/hq_palm_detect.cfg \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/hqcfg/hq_palm_detect.param:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hqcfg/hq_palm_detect.param \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/mfnr_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mfnr_arrays.json \
    vendor/samsung/gta9/proprietary/vendor/etc/camera/night_arrays.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/night_arrays.json \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/MNL_Config.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/deleteLogCommands:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/deleteLogCommands \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/mnl.prop:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/mnl.prop \
    vendor/samsung/gta9/proprietary/vendor/etc/gnss/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/mpe.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.gps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/mtklog.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtklog.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/teegris_v4.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/teegris_v4.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vaultkeeper_common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vaultkeeper_common.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.0-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.samsung.hardware.miscpower@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.miscpower@2.0-service.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.samsung.rilchip.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.mediatek.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/samsung/gta9/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/samsung/gta9/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/samsung/gta9/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/samsung/gta9/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/samsung/gta9/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/samsung/gta9/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/samsung/gta9/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_criteria.csv \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_new_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_new_criteria.csv \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_new_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_new_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_cd_inx_new_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_cd_inx_new_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_gx_hsd_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_gx_hsd_criteria.csv \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_gx_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_gx_hsd_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_gx_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_gx_hsd_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_lc_hkc_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_lc_hkc_criteria.csv \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_lc_hkc_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_lc_hkc_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_lc_hkc_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_lc_hkc_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_xx_inx_criteria.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xx_inx_criteria.csv \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_xx_inx_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xx_inx_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/hx83102e_xx_inx_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hx83102e_xx_inx_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/jd9366tc_xx_hkc_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/jd9366tc_xx_hkc_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/jd9366tc_xx_hkc_ito.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/jd9366tc_xx_hkc_ito.txt \
    vendor/samsung/gta9/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6627_fm_channel_param.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_channel_param.dat \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6627_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6627_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v2_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff_tx.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6630_fm_v2_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch_tx.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6631_fm_channel_param.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_channel_param.dat \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6632_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6632_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6635_fm_channel_param.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_channel_param.dat \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/nl9951_gx_boe.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nl9951_gx_boe.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/nt36523d_lc_hsd_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523d_lc_hsd_firmware.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/nt36523d_lc_hsd_mpfw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nt36523d_lc_hsd_mpfw.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_bt_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1d_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_bt_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1e_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_mcu_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1d_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_mcu_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1e_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_wifi_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1d_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc2_2_ram_wifi_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1e_1_hdr.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/samsung/gta9/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/samsung/gta9/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-000000010081:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000010081 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-000000020081:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000020081 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-000048444350:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000048444350 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-0000534b504d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-0000534b504d \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-474154454b45:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-474154454b45 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-496343475244:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-496343475244 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-4b45594d5354:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-4b45594d5354 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-53454d655345:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-53454d655345 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-54496473706c:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-54496473706c \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-544974684c6c:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-544974684c6c \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-564c544b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-564c544b5052 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-6b6e78677564:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6b6e78677564 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-0000-0000-0000-6d73745f5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d73745f5441 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4875-4171-496e-466163656871:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4875-4171-496e-466163656871 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4875-4171-496e-4772446d4871:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4875-4171-496e-4772446d4871 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4d54-4b5f-4246-444150437461:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-444150437461 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4d54-4b5f-4246-44524d4b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-44524d4b5052 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4d54-4b5f-4246-534d454d5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-534d454d5441 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4d54-4b5f-4246-57564e544100:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-57564e544100 \
    vendor/samsung/gta9/proprietary/vendor/tee/00000000-4d54-4b5f-4246-72706d627461:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-4d54-4b5f-4246-72706d627461 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-0000-0000-0000-494363447256:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-494363447256 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-0000-0000-0000-4d53546d7374:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-4d53546d7374 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-0000-0000-0000-564c544b4456:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-564c544b4456 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4875-4171-496e-487146436476:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4875-4171-496e-487146436476 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-444150436472:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-444150436472 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-445248444350:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-445248444350 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-44524d4b5044:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-44524d4b5044 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-534d45647276:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-534d45647276 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/00000000-4d54-4b5f-4246-57564e647276:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-4d54-4b5f-4246-57564e647276 \
    vendor/samsung/gta9/proprietary/vendor/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:$(TARGET_COPY_OUT_VENDOR)/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_ \
    vendor/samsung/gta9/proprietary/vendor/tee/tui/resolution_common/ID00000100:$(TARGET_COPY_OUT_VENDOR)/tee/tui/resolution_common/ID00000100

PRODUCT_PACKAGES += \
    libbase \
    android.hardware.thermal@2.0-impl \
    libaedv \
    libfloatingfeature \
    libgz_gp_client \
    libgz_uree \
    libpower_timer \
    libsecnativefeature \
    libsemnativecarrierfeature \
    libteecl \
    libthha \
    libuuid_vendor \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    libGLES_meow \
    libMEOW_data \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    android.hardware.bluetooth@1.1-impl-mediatek \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    gatekeeper.mt6789 \
    gps.default \
    hwcomposer.mtk_common \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mt6789 \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    vendor.samsung.hardware.gnss@2.0-impl \
    libBSTBeauty \
    libBSTBeautyBokeh \
    libBstBeauty_Impl \
    libCamera_a0901backsc800cslymipiraw_AI_Scene13 \
    libCamera_a0901backsc800cslymipiraw_AI_Scene14 \
    libCamera_a0901backsc800cslymipiraw_AI_Scene15 \
    libCamera_a0901backsc800cslymipiraw_AI_Scene7 \
    libCamera_a0901backsc800cslymipiraw_Night_Capture \
    libCamera_a0901backsc800cslymipiraw_Scene_Beauty \
    libCamera_a0901backsc800cslymipiraw_Scene_Panorama \
    libCamera_a0901backsc800cslymipiraw_Scene_Portrait \
    libCamera_a0901backsc800cslymipiraw_Scene_Preview_AVERAGE \
    libCamera_a0901backsc800cslymipiraw_Scene_Preview_SPOT \
    libCamera_a0901backsc800cslymipiraw_Video_1080_60 \
    libCamera_a0901frontsc201cslymipiraw_Scene_BSTBeauty_capture \
    libCamera_a0901frontsc201cslymipiraw_Scene_BSTHDR_capture \
    libCamera_a0901frontsc201cslymipiraw_Scene_BSTSuperNight_capture \
    libCamera_a0901frontsc201cslymipiraw_Scene_zoom_capture \
    libCamera_a0901frontsc201cslymipiraw_Scene_zoom_preview \
    libCamera_a0902backhi846stmipiraw_AI_Scene13 \
    libCamera_a0902backhi846stmipiraw_AI_Scene14 \
    libCamera_a0902backhi846stmipiraw_AI_Scene15 \
    libCamera_a0902backhi846stmipiraw_AI_Scene7 \
    libCamera_a0902backhi846stmipiraw_Night_Capture \
    libCamera_a0902backhi846stmipiraw_Scene_Beauty \
    libCamera_a0902backhi846stmipiraw_Scene_Panorama \
    libCamera_a0902backhi846stmipiraw_Scene_Portrait \
    libCamera_a0902backhi846stmipiraw_Scene_Preview_AVERAGE \
    libCamera_a0902backhi846stmipiraw_Scene_Preview_SPOT \
    libCamera_a0902backhi846stmipiraw_Video_1080_60 \
    libCamera_a0902frontc2599cxtmipiraw_Scene_BSTBeauty_capture \
    libCamera_a0902frontc2599cxtmipiraw_Scene_BSTHDR_capture \
    libCamera_a0902frontc2599cxtmipiraw_Scene_BSTHDR_preview \
    libCamera_a0902frontc2599cxtmipiraw_Scene_BSTSuperNight_capture \
    libCamera_a0902frontc2599cxtmipiraw_Scene_zoom_capture \
    libCamera_a0902frontc2599cxtmipiraw_Scene_zoom_preview \
    libCamera_a0903backc8490xsjmipiraw_AI_Scene13 \
    libCamera_a0903backc8490xsjmipiraw_AI_Scene14 \
    libCamera_a0903backc8490xsjmipiraw_AI_Scene15 \
    libCamera_a0903backc8490xsjmipiraw_AI_Scene7 \
    libCamera_a0903backc8490xsjmipiraw_Night_Capture \
    libCamera_a0903backc8490xsjmipiraw_Scene_Beauty \
    libCamera_a0903backc8490xsjmipiraw_Scene_Panorama \
    libCamera_a0903backc8490xsjmipiraw_Scene_Portrait \
    libCamera_a0903backc8490xsjmipiraw_Scene_Preview_AVERAGE \
    libCamera_a0903backc8490xsjmipiraw_Scene_Preview_SPOT \
    libCamera_a0903backc8490xsjmipiraw_Video_1080_60 \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_BSTBeauty_capture \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_BSTHDR_capture \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_BSTSuperNight_capture \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_zoom_capture \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_zoom_preview \
    libCamera_a0904backsc800csstmipiraw_Night_Capture \
    libCamera_a0904backsc800csstmipiraw_Video_1080_60 \
    libCamera_a0904backsc820csstmipiraw_AI_Scene13 \
    libCamera_a0904backsc820csstmipiraw_AI_Scene14 \
    libCamera_a0904backsc820csstmipiraw_AI_Scene15 \
    libCamera_a0904backsc820csstmipiraw_AI_Scene7 \
    libCamera_a0904backsc820csstmipiraw_Night_Capture \
    libCamera_a0904backsc820csstmipiraw_Scene_Beauty \
    libCamera_a0904backsc820csstmipiraw_Scene_Panorama \
    libCamera_a0904backsc820csstmipiraw_Scene_Portrait \
    libCamera_a0904backsc820csstmipiraw_Scene_Preview_AVERAGE \
    libCamera_a0904backsc820csstmipiraw_Scene_Preview_SPOT \
    libCamera_a0904backsc820csstmipiraw_Video_1080_60 \
    libJpgEncPipe \
    libMtkSpeechEnh \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libVendorSemDataProps \
    libVendorSemTelephonyProps \
    lib_iir \
    libaal_key \
    libalsautils-v31 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarcsoft_MFNR \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libbwc \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.n3d \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.warp \
    libcares_naptr \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdsms_vendor \
    libengmode_client \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libheichal \
    libhfmanager \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libion_mtk \
    libion_ulit \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libksensor \
    libladder \
    libminiui \
    libmipc \
    libmmagent \
    libmml \
    libmpbase \
    libmsbc_mtk \
    libmtk-ril \
    libmtkares \
    libmtkcam_pipelinepolicy-aov \
    libmtkconfig \
    libmtkconfigutils \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtklimiter_vendor \
    libmtknetcap \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libpixelflinger \
    libpqframework \
    libratconfig \
    libremosaic_wrapper \
    libril_sem \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libsec-ril \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libstork_shared \
    libsysenv \
    libtensorflowlite \
    libtlcWidevineModularDrm \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libviagpsrpc \
    libvkmanager_vendor \
    libvkservice \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    a0901backsc800csly_mipi_raw_IdxMgr \
    a0901backsc800csly_mipi_raw_tuning \
    a0901frontsc201csly_mipi_raw_IdxMgr \
    a0901frontsc201csly_mipi_raw_tuning \
    a0902backhi846st_mipi_raw_IdxMgr \
    a0902backhi846st_mipi_raw_tuning \
    a0902frontc2599cxt_mipi_raw_IdxMgr \
    a0902frontc2599cxt_mipi_raw_tuning \
    a0903backc8490xsj_mipi_raw_IdxMgr \
    a0903backc8490xsj_mipi_raw_tuning \
    a0903frontbf2257xsj_mipi_raw_IdxMgr \
    a0903frontbf2257xsj_mipi_raw_tuning \
    a0904backsc800csst_mipi_raw_IdxMgr \
    a0904backsc800csst_mipi_raw_tuning \
    a0904backsc820csst_mipi_raw_IdxMgr \
    a0904backsc820csst_mipi_raw_tuning \
    arm.graphics-V1-ndk_platform \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.custom.ae \
    lib3a.flash \
    lib3a.flicker \
    lib3a.log \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_a0901backsc800cslymipiraw_E2EHDR_Preview \
    libCamera_a0901backsc800cslymipiraw_E2EHDR_Video \
    libCamera_a0901backsc800cslymipiraw_Face_Capture \
    libCamera_a0901backsc800cslymipiraw_Flash_Capture \
    libCamera_a0901backsc800cslymipiraw_HDR_Capture \
    libCamera_a0901backsc800cslymipiraw_HDR_Preview \
    libCamera_a0901backsc800cslymipiraw_HDR_Video \
    libCamera_a0901backsc800cslymipiraw_N3D_Capture \
    libCamera_a0901backsc800cslymipiraw_N3D_Preview \
    libCamera_a0901backsc800cslymipiraw_N3D_Video \
    libCamera_a0901backsc800cslymipiraw_P1_YUV \
    libCamera_a0901backsc800cslymipiraw_Scene_Capture \
    libCamera_a0901backsc800cslymipiraw_Scene_Capture_4cell \
    libCamera_a0901backsc800cslymipiraw_Scene_Preview \
    libCamera_a0901backsc800cslymipiraw_Scene_Preview_4k \
    libCamera_a0901backsc800cslymipiraw_Scene_Preview_ZSD_Flash \
    libCamera_a0901backsc800cslymipiraw_Video_1080 \
    libCamera_a0901backsc800cslymipiraw_Video_4k \
    libCamera_a0901frontsc201cslymipiraw_Scene_Capture \
    libCamera_a0901frontsc201cslymipiraw_Scene_Preview \
    libCamera_a0901frontsc201cslymipiraw_Video_4k \
    libCamera_a0902backhi846stmipiraw_E2EHDR_Preview \
    libCamera_a0902backhi846stmipiraw_E2EHDR_Video \
    libCamera_a0902backhi846stmipiraw_Face_Capture \
    libCamera_a0902backhi846stmipiraw_Flash_Capture \
    libCamera_a0902backhi846stmipiraw_HDR_Capture \
    libCamera_a0902backhi846stmipiraw_HDR_Preview \
    libCamera_a0902backhi846stmipiraw_HDR_Video \
    libCamera_a0902backhi846stmipiraw_N3D_Capture \
    libCamera_a0902backhi846stmipiraw_N3D_Preview \
    libCamera_a0902backhi846stmipiraw_N3D_Video \
    libCamera_a0902backhi846stmipiraw_P1_YUV \
    libCamera_a0902backhi846stmipiraw_Scene_Capture \
    libCamera_a0902backhi846stmipiraw_Scene_Capture_4cell \
    libCamera_a0902backhi846stmipiraw_Scene_Preview \
    libCamera_a0902backhi846stmipiraw_Scene_Preview_4k \
    libCamera_a0902backhi846stmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_a0902backhi846stmipiraw_Video_1080 \
    libCamera_a0902backhi846stmipiraw_Video_4k \
    libCamera_a0902frontc2599cxtmipiraw_Scene_Capture \
    libCamera_a0902frontc2599cxtmipiraw_Scene_Preview \
    libCamera_a0902frontc2599cxtmipiraw_Video_4k \
    libCamera_a0903backc8490xsjmipiraw_E2EHDR_Preview \
    libCamera_a0903backc8490xsjmipiraw_E2EHDR_Video \
    libCamera_a0903backc8490xsjmipiraw_Face_Capture \
    libCamera_a0903backc8490xsjmipiraw_Flash_Capture \
    libCamera_a0903backc8490xsjmipiraw_HDR_Capture \
    libCamera_a0903backc8490xsjmipiraw_HDR_Preview \
    libCamera_a0903backc8490xsjmipiraw_HDR_Video \
    libCamera_a0903backc8490xsjmipiraw_N3D_Capture \
    libCamera_a0903backc8490xsjmipiraw_N3D_Preview \
    libCamera_a0903backc8490xsjmipiraw_N3D_Video \
    libCamera_a0903backc8490xsjmipiraw_P1_YUV \
    libCamera_a0903backc8490xsjmipiraw_Scene_Capture \
    libCamera_a0903backc8490xsjmipiraw_Scene_Capture_4cell \
    libCamera_a0903backc8490xsjmipiraw_Scene_Preview \
    libCamera_a0903backc8490xsjmipiraw_Scene_Preview_4k \
    libCamera_a0903backc8490xsjmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_a0903backc8490xsjmipiraw_Video_1080 \
    libCamera_a0903backc8490xsjmipiraw_Video_4k \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_Capture \
    libCamera_a0903frontbf2257xsjmipiraw_Scene_Preview \
    libCamera_a0903frontbf2257xsjmipiraw_Video_4k \
    libCamera_a0904backsc800csstmipiraw_E2EHDR_Preview \
    libCamera_a0904backsc800csstmipiraw_E2EHDR_Video \
    libCamera_a0904backsc800csstmipiraw_Face_Capture \
    libCamera_a0904backsc800csstmipiraw_Flash_Capture \
    libCamera_a0904backsc800csstmipiraw_HDR_Capture \
    libCamera_a0904backsc800csstmipiraw_HDR_Preview \
    libCamera_a0904backsc800csstmipiraw_HDR_Video \
    libCamera_a0904backsc800csstmipiraw_N3D_Capture \
    libCamera_a0904backsc800csstmipiraw_N3D_Preview \
    libCamera_a0904backsc800csstmipiraw_N3D_Video \
    libCamera_a0904backsc800csstmipiraw_P1_YUV \
    libCamera_a0904backsc800csstmipiraw_Scene_Capture \
    libCamera_a0904backsc800csstmipiraw_Scene_Capture_4cell \
    libCamera_a0904backsc800csstmipiraw_Scene_Preview \
    libCamera_a0904backsc800csstmipiraw_Scene_Preview_4k \
    libCamera_a0904backsc800csstmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_a0904backsc800csstmipiraw_Video_1080 \
    libCamera_a0904backsc800csstmipiraw_Video_4k \
    libCamera_a0904backsc820csstmipiraw_E2EHDR_Preview \
    libCamera_a0904backsc820csstmipiraw_E2EHDR_Video \
    libCamera_a0904backsc820csstmipiraw_Face_Capture \
    libCamera_a0904backsc820csstmipiraw_Flash_Capture \
    libCamera_a0904backsc820csstmipiraw_HDR_Capture \
    libCamera_a0904backsc820csstmipiraw_HDR_Preview \
    libCamera_a0904backsc820csstmipiraw_HDR_Video \
    libCamera_a0904backsc820csstmipiraw_N3D_Capture \
    libCamera_a0904backsc820csstmipiraw_N3D_Preview \
    libCamera_a0904backsc820csstmipiraw_N3D_Video \
    libCamera_a0904backsc820csstmipiraw_P1_YUV \
    libCamera_a0904backsc820csstmipiraw_Scene_Capture \
    libCamera_a0904backsc820csstmipiraw_Scene_Capture_4cell \
    libCamera_a0904backsc820csstmipiraw_Scene_Preview \
    libCamera_a0904backsc820csstmipiraw_Scene_Preview_4k \
    libCamera_a0904backsc820csstmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_a0904backsc820csstmipiraw_Video_1080 \
    libCamera_a0904backsc820csstmipiraw_Video_4k \
    libDR \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libaaa_ltm \
    libaaa_ltmx \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaidepth_tuning \
    libaiselector \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.lsc \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libdip_drv \
    libdip_postproc \
    libdpframework \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmnl \
    libmsnr \
    libmtk_drvb \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libstereoinfoaccessor_vsdof \
    libvainr_model \
    sensors.grip \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    vendor.samsung.frameworks.security.dsms-V1-ndk_platform \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.miscpower@2.0 \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    vendor.samsung.hardware.radio.bridge@2.0 \
    vendor.samsung.hardware.radio.bridge@2.1 \
    vendor.samsung.hardware.radio.channel@2.0 \
    vendor.samsung.hardware.radio@2.0 \
    vendor.samsung.hardware.radio@2.1 \
    vendor.samsung.hardware.radio@2.2 \
    vendor.samsung.hardware.security.vaultkeeper@2.0 \
    vendor.samsung.hardware.thermal@1.0 \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    vendor.mediatek.hardware.videotelephony-V1-ndk \
    vendor.mediatek.hardware.videotelephony@1.0 \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    vaultkeeper_manifest.xml \
    vendor.samsung.hardware.radio.exclude.mediatek.xml \
    vendor.samsung.hardware.radio.exclude_ship.mediatek.xml \
    vendor.samsung.hardware.radio_manifest_1_31.xml \
    vendor.samsung.hardware.sehradio_manifest_1_31.xml \
    bip_ap \
    ccci_mdinit \
    ccci_rpcd \
    chipinfo \
    conninfra_loader \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    camerahalserver \
    rild \
    tetheroffloadservice \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.mtkpower@1.0-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.samsung.hardware.gnss@2.0-service \
    vendor.samsung.hardware.miscpower@2.0-service \
    vtservice_hidl \
    mnld \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    thermal_core \
    thermal_intf \
    tzdaemon \
    tzts_daemon \
    vaultkeeperd \
    vendor.samsung.hardware.security.vaultkeeper@2.0-service \
    wlan_assistant \
    vtservice

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_primary_mt6895_so \
    vendor_lib64_hw_audio_r_submix_mt6789_so \
    vendor_lib64_hw_android_hardware_camera_provider@2_6-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_common_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_a0901backsc800csly_mipi_raw_IdxMgr_so \
    vendor_lib64_a0901backsc800csly_mipi_raw_tuning_so \
    vendor_lib64_a0901frontsc201csly_mipi_raw_IdxMgr_so \
    vendor_lib64_a0901frontsc201csly_mipi_raw_tuning_so \
    vendor_lib64_a0902backhi846st_mipi_raw_IdxMgr_so \
    vendor_lib64_a0902backhi846st_mipi_raw_tuning_so \
    vendor_lib64_a0902frontc2599cxt_mipi_raw_IdxMgr_so \
    vendor_lib64_a0902frontc2599cxt_mipi_raw_tuning_so \
    vendor_lib64_a0903backc8490xsj_mipi_raw_IdxMgr_so \
    vendor_lib64_a0903backc8490xsj_mipi_raw_tuning_so \
    vendor_lib64_a0903frontbf2257xsj_mipi_raw_IdxMgr_so \
    vendor_lib64_a0903frontbf2257xsj_mipi_raw_tuning_so \
    vendor_lib64_a0904backsc800csst_mipi_raw_IdxMgr_so \
    vendor_lib64_a0904backsc800csst_mipi_raw_tuning_so \
    vendor_lib64_a0904backsc820csst_mipi_raw_IdxMgr_so \
    vendor_lib64_a0904backsc820csst_mipi_raw_tuning_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libSonyIMX230PdafLibrary_so \
    vendor_lib64_libSonyIMX230PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX338PdafLibrary_so \
    vendor_lib64_libSonyIMX338PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX386PdafLibrary_so \
    vendor_lib64_libSonyIMX386PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX519PdafLibrary_so \
    vendor_lib64_libSonyIMX519PdafLibraryWrapper_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_50_so \
    vendor_lib64_libcam_hal3a_v3_nvram_50_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_iopipe_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamdrv_isp_so \
    vendor_lib64_libcamdrv_tuning_mgr_so \
    vendor_lib64_libcamdrv_twin_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libdip_drv_so \
    vendor_lib64_libdip_postproc_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_3dnr_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_lmv_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libimageio_so \
    vendor_lib64_libimageio_plat_drv_so \
    vendor_lib64_libimageio_plat_pipe_so \
    vendor_lib64_liblpcnr_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmsnr_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_util_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_3rdparty_core_so \
    vendor_lib64_libmtkcam_3rdparty_customer_so \
    vendor_lib64_libmtkcam_3rdparty_mtk_so \
    vendor_lib64_libmtkcam_3rdparty_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_device3_app_so \
    vendor_lib64_libmtkcam_device3_hal_so \
    vendor_lib64_libmtkcam_device3_hidl_so \
    vendor_lib64_libmtkcam_device3_hidlutils_so \
    vendor_lib64_libmtkcam_device3_utils_so \
    vendor_lib64_libmtkcam_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_fdvt_so \
    vendor_lib64_libmtkcam_featurepolicy_so \
    vendor_lib64_libmtkcam_featureutils_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_imem_so \
    vendor_lib64_libmtkcam_imgbuf_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_mfb_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_owe_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_so \
    vendor_lib64_libmtkcam_pipelinemodel_adapter_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_isp_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinemodel_zsl_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_rsc_so \
    vendor_lib64_libmtkcam_scenariorecorder_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_libvainr_model_so
